server:
 port: 8888
 
 
spring:
  profiles:
    active: native
    
  cloud:
    config:
      server: 
        native:
          search-locations: /home/ubuntu20/dev/workspace/lab/springCloudAlura
          
